<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>tw.elliot</groupId>
  <artifactId>oauth</artifactId>
  <version>revision</version>
  <packaging>pom</packaging>
  <name>oauth</name>
  <modules>
    <module>parent</module>
    <module>clientCredentials/server/ccOauthServer</module>
    <module>clientCredentials/server/ccResourceServer</module>
    <module>clientCredentials/client/ccResourceClient</module>
    <module>pkce/server/pkceOauthServer</module>
    <module>pkce/server/pkceResourceServer</module>
    <module>pkce/client/pkceResourceClient</module>
  </modules>

</project>
