server:
  port: 8081

spring:
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    web: DEBUG
    security: DEBUG
    org:
      springframework:
        security: DEBUG
###
#security:
#  oauth2:
#    client:
#      client-id: app
#      client-secret: 654321